# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/great/Unreal Engine/UE_5.4.4
GAMEPROJECTFILE =/home/great/Documents/GitHub/EnginesCourseProject/EnginesCourseProject.uproject

TARGETS = \
	EnginesCourseProject-Linux-DebugGame  \
	EnginesCourseProject-Linux-Shipping  \
	EnginesCourseProject \
	EnginesCourseProjectEditor-Linux-DebugGame  \
	EnginesCourseProjectEditor-Linux-Shipping  \
	EnginesCourseProjectEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend EnginesCourseProjectEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug EnginesCourseProjectEditor-Linux-Debug


EnginesCourseProject-Linux-DebugGame:
	 $(PROJECTBUILD) EnginesCourseProject Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

EnginesCourseProject-Linux-Shipping:
	 $(PROJECTBUILD) EnginesCourseProject Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

EnginesCourseProject:
	 $(PROJECTBUILD) EnginesCourseProject Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

EnginesCourseProjectEditor-Linux-DebugGame:
	 $(PROJECTBUILD) EnginesCourseProjectEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

EnginesCourseProjectEditor-Linux-Shipping:
	 $(PROJECTBUILD) EnginesCourseProjectEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

EnginesCourseProjectEditor:
	 $(PROJECTBUILD) EnginesCourseProjectEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
